format YEAR     %4.0f
format PUMFID   %5.0f
format PERSONID %20s
format FWEIGHT  %10.4f
format PROV     %2s
format USZGAP   %2s
format MBMREGP  %2s
format AGEGP    %2s
format SEX      %1s
format MARSTP   %2s
format CMPHI    %1s
format HLEV2G   %1s
format STUDTFP  %1s
format FLLPRTP  %1s
format FWORKED  %1s
format SCSUM    %2s
format ALFST    %2s
format WKSEM    %2.0f
format WKSUEM   %2.0f
format WKSNLF   %2.0f
format USHRWK   %5.1f
format ALHRWK   %4.0f
format FPDWK    %1s
format FSEMP    %1s
format FUNFW    %1s
format IMMST    %1s
format YRIMMG   %1s
format ALIMO    %8.0f
format ALIP     %8.0f
format ATINC    %8.0f
format CAPGN    %8.0f
format CCAR     %8.0f
format CHFED    %8.0f
format CHPRV    %8.0f
format CHTXB    %8.0f
format CPQPP    %8.0f
format CQPC     %8.0f
format EARNG    %8.0f
format EIPR     %8.0f
format FDITX    %8.0f
format GI       %8.0f
format GSTXC    %8.0f
format GTR      %8.0f
format INCTX    %8.0f
format INVA     %8.0f
format MAJRI    %2s
format MTINC    %8.0f
format OAS      %8.0f
format OASGI    %8.0f
format OGOVTR   %8.0f
format OTHINC   %8.0f
format OTTXM    %8.0f
format PEN      %8.0f
format PENGIV   %8.0f
format PENREC   %8.0f
format PHPR     %8.0f
format PRPEN    %8.0f
format PVITX    %8.0f
format PVTXC    %8.0f
format RPPC     %8.0f
format RSPWI    %8.0f
format SAPIS    %8.0f
format SEMP     %8.0f
format TTINC    %8.0f
format UDPD     %8.0f
format UIBEN    %8.0f
format WGSAL    %8.0f
format WKRCP    %8.0f
format EFID     %20s
format EFSIZE   %2.0f
format EFTYP    %2s
format EFMJIE   %1s
format EFMJIEH  %1s
format EFRMJIG  %1s
format EFAGOFMP %2s
format EFAGYFMP %2s
format EFMJSI   %2s
format EFALIMO  %8.0f
format EFALIP   %8.0f
format EFATINC  %8.0f
format EFCAPGN  %8.0f
format EFCCAR   %8.0f
format EFCHFED  %8.0f
format EFCHPRV  %8.0f
format EFCHTXB  %8.0f
format EFCPQPP  %8.0f
format EFCQPC   %8.0f
format EFEARNG  %8.0f
format EFEIPR   %8.0f
format EFFDITX  %8.0f
format EFGI     %8.0f
format EFGSTXC  %8.0f
format EFGTR    %8.0f
format EFINCTX  %8.0f
format EFINVA   %8.0f
format EFMBIN18 %8.0f
format EFMTINC  %8.0f
format EFOAS    %8.0f
format EFOASGI  %8.0f
format EFOGOVTR %8.0f
format EFOTHINC %8.0f
format EFOTTXM  %8.0f
format EFPEN    %8.0f
format EFPENGIV %8.0f
format EFPENREC %8.0f
format EFPHPR   %8.0f
format EFPRPEN  %8.0f
format EFPVITX  %8.0f
format EFPVTXC  %8.0f
format EFRPPC   %8.0f
format EFRSPWI  %8.0f
format EFSAPIS  %8.0f
format EFSEMP   %8.0f
format EFTTINC  %8.0f
format EFUDPD   %8.0f
format EFUIBEN  %8.0f
format EFWGSAL  %8.0f
format EFWKRCP  %8.0f
format CFID     %21s
format CFSIZE   %2.0f
format CFCOMP   %2s
format CFMJIE   %1s
format CFMJIEH  %1s
format CFRMJIG  %1s
format CFAGOFMP %2s
format CFAGYFMP %2s
format CFMJSI   %2s
format CFALIMO  %8.0f
format CFALIP   %8.0f
format CFATINC  %8.0f
format CFCAPGN  %8.0f
format CFCCAR   %8.0f
format CFCHFED  %8.0f
format CFCHPRV  %8.0f
format CFCHTXB  %8.0f
format CFCPQPP  %8.0f
format CFCQPC   %8.0f
format CFEARNG  %8.0f
format CFEIPR   %8.0f
format CFFDITX  %8.0f
format CFGI     %8.0f
format CFGSTXC  %8.0f
format CFGTR    %8.0f
format CFINCTX  %8.0f
format CFINVA   %8.0f
format CFMTINC  %8.0f
format CFOAS    %8.0f
format CFOASGI  %8.0f
format CFOGOVTR %8.0f
format CFOTHINC %8.0f
format CFOTTXM  %8.0f
format CFPEN    %8.0f
format CFPENGIV %8.0f
format CFPENREC %8.0f
format CFPHPR   %8.0f
format CFPRPEN  %8.0f
format CFPVITX  %8.0f
format CFPVTXC  %8.0f
format CFRPPC   %8.0f
format CFRSPWI  %8.0f
format CFSAPIS  %8.0f
format CFSEMP   %8.0f
format CFTTINC  %8.0f
format CFUDPD   %8.0f
format CFUIBEN  %8.0f
format CFWGSAL  %8.0f
format CFWKRCP  %8.0f
format HHSIZE   %2.0f
format HHCOMP   %1s
format HHMJIE   %1s
format LICODA   %5.1f
format LICOFA   %1s
format LICODB   %5.1f
format LICOFB   %1s
format LIMSDA   %5.1f
format LIMSFA   %1s
format MBSCD18  %5.1f
format MBSCF18  %1s
format DWLTYP   %1s
format DWTENR   %1s
format REPA     %1s
format SUIT     %1s
format MORTG    %1s
format MORTGM   %8.0f
format CONDMP   %8.0f
format RENTM    %8.0f
format RNSUB    %1s
format CHNEED   %1s
format FSCADLTM %1s
format FSCCHLDM %1s
format FSCHHLDM %1s
format VERDATE  %10s
