label variable YEAR      "Année de référence"
label variable PUMFID    "Identificateur du ménage"
label variable PERSONID  "Identificateur de la personne"
label variable FWEIGHT   "Poids final"
label variable PROV      "Province"
label variable USZGAP    "Taille ajustée du secteur de résidence"
label variable MBMREGP   "Région de la Mesure du panier de consommation (MPC)"
label variable AGEGP     "Groupe d'âge au 31 décembre de l'année de référence"
label variable SEX       "Sexe"
label variable MARSTP    "État matrimonial"
label variable CMPHI     "Indicateur - Études secondaires complétées"
label variable HLEV2G    "Plus haut niveau de scolarité de la personne, 2e regroupement"
label variable STUDTFP   "Ind - A fréquenté école, collège, cégep ou univ. pendant année réf"
label variable FLLPRTP   "Études à temps plein ou à temps partiel pendant année réf"
label variable FWORKED   "Ind - Personne avait un emploi pendant année réf"
label variable SCSUM     "Sommaire annuel du temps travaillé pendant année réf"
label variable ALFST     "Statut d'activité annuel"
label variable WKSEM     "Nombre de semaines avec emploi pendant année réf"
label variable WKSUEM    "Nombre de semaines en chômage pendant année réf"
label variable WKSNLF    "Nombre de semaines hors de la population active pendant année réf"
label variable USHRWK    "Heures hab. moyennes trav. par semaine à tous emplois pend. année réf"
label variable ALHRWK    "Total des heures habituellement trav. à tous emplois pendant année réf"
label variable FPDWK     "Ind - Personne a été employée rémunérée pendant année réf"
label variable FSEMP     "Ind - Travail autonome pendant année réf"
label variable FUNFW     "Ind - Travail familial non rémunéré pendant année réf"
label variable IMMST     "Indicateur - Personne est une immigrante reçue"
label variable YRIMMG    "Nombre d'années depuis l'immigration au Canada, regroupement"
label variable ALIMO     "Pension alimentaire reçue"
label variable ALIP      "Pension alimentaire payée"
label variable ATINC     "Revenu après impôt"
label variable CAPGN     "Gains en capital imposables"
label variable CCAR      "Frais de garde d'enfants"
label variable CHFED     "Total des prestations fédérales pour enfants"
label variable CHPRV     "Total des prestations provinciales pour enfants"
label variable CHTXB     "Total des prestations fédérales et provinciales pour enfants"
label variable CPQPP     "Prestations du RPC/RRQ"
label variable CQPC      "Cotisations au RPC/RRQ"
label variable EARNG     "Revenu d'emploi"
label variable EIPR      "Cotisations à l'assurance-emploi"
label variable FDITX     "Impôt fédéral (Québec : impôt fédéral moins abattement du Québec)"
label variable GI        "Supplément de revenu garanti (prog. féd. Sécurité de vieillesse)"
label variable GSTXC     "Crédit TPS/TVH fédéral (exclut crédits pour taxe de vente prov.)"
label variable GTR       "Transferts gouvernementaux, fédéraux et provinciaux"
label variable INCTX     "Impôt sur le revenu, fédéral et provincial"
label variable INVA      "Revenu de placements"
label variable MAJRI     "Principale source de revenu"
label variable MTINC     "Revenu du marché"
label variable OAS       "Pension de la Sécurité de la vieillesse"
label variable OASGI     "Total des prestations de Sécurité de la vieillesse"
label variable OGOVTR    "Autres transferts gouvernementaux"
label variable OTHINC    "Autres revenus"
label variable OTTXM     "Autres revenus imposables"
label variable PEN       "Pensions de retraite privées (comprend fractionn. rev. de pension)"
label variable PENGIV    "Déduction pour le montant de pension fractionné"
label variable PENREC    "Montant de pension fractionné"
label variable PHPR      "Primes d'assurance-maladie publique"
label variable PRPEN     "Pensions de retraite privées"
label variable PVITX     "Impôt provincial sur le revenu"
label variable PVTXC     "Crédits d'impôt provinciaux"
label variable RPPC      "Cotisations à un régime de pension agréé"
label variable RSPWI     "Retraits d'un REER"
label variable SAPIS     "Prestations d'assistance sociale"
label variable SEMP      "Revenu net d'un travail autonome"
label variable TTINC     "Revenu total avant impôt"
label variable UDPD      "Cotisations syndicales (et autres primes professionnelles)"
label variable UIBEN     "Prestations d'assurance-emploi"
label variable WGSAL     "Salaires et traitements avant déductions"
label variable WKRCP     "Indemnités pour accidents du travail"
label variable EFID      "Identificateur de la famille économique"
label variable EFSIZE    "Taille de la famille économique"
label variable EFTYP     "Type de famille économique"
label variable EFMJIE    "Ind - Soutien économique principal de la famille économique"
label variable EFMJIEH   "Ind - La famille écon. inclut le soutien écon. princ. du ménage"
label variable EFRMJIG   "Lien de parenté avec soutien écon. principal de la fam. écon., rgp"
label variable EFAGOFMP  "Groupe d’âge du membre le plus âgé de la famille économique"
label variable EFAGYFMP  "Groupe d’âge du membre le plus jeune de la fam. économique"
label variable EFMJSI    "Principale source de revenu pour la famille économique"
label variable EFALIMO   "FÉ - Pension alimentaire reçue"
label variable EFALIP    "FÉ - Pension alimentaire payée"
label variable EFATINC   "FÉ - Revenu après impôt"
label variable EFCAPGN   "FÉ - Gains en capital imposables"
label variable EFCCAR    "FÉ - Frais de garde d'enfants"
label variable EFCHFED   "FÉ - Total des prestations fédérales pour enfants"
label variable EFCHPRV   "FÉ - Total des prestations provinciales pour enfants"
label variable EFCHTXB   "FÉ - Total des prestations fédérales et provinciales pour enfants"
label variable EFCPQPP   "FÉ - Prestations du RPC/RRQ"
label variable EFCQPC    "FÉ - Cotisations au RPC/RRQ"
label variable EFEARNG   "FÉ - Revenu d'emploi"
label variable EFEIPR    "FÉ- Cotisations à l'assurance-emploi"
label variable EFFDITX   "FÉ - Impôt fédéral pour résidents du Québec"
label variable EFGI      "FÉ - Supplément de revenu garanti (prog. féd. Sécurité de vieillesse)"
label variable EFGSTXC   "FÉ - Crédit TPS/TVH fédéral (exclut crédits pour taxe de vente prov.)"
label variable EFGTR     "FÉ - Transferts gouvernementaux, fédéraux et provinciaux"
label variable EFINCTX   "FÉ - Impôt sur le revenu, fédéral et provincial"
label variable EFINVA    "FÉ - Revenu de placements"
label variable EFMBIN18  "FÉ - Concept de revenu disponible pour la MPC (base de 2018)"
label variable EFMTINC   "FÉ - Revenu du marché"
label variable EFOAS     "FÉ - Pension de la Sécurité de la vieillesse"
label variable EFOASGI   "FÉ - Total des prestations de Sécurité de la vieillesse"
label variable EFOGOVTR  "FÉ - Autres transferts gouvernementaux"
label variable EFOTHINC  "FÉ - Autres revenus"
label variable EFOTTXM   "FÉ - Autres revenus imposables"
label variable EFPEN     "FÉ - Pensions de retraite privées (comprend fractionn. rev. de pension"
label variable EFPENGIV  "FÉ - Déduction pour le montant de pension fractionné"
label variable EFPENREC  "FÉ - Montant de pension fractionné"
label variable EFPHPR    "FÉ - Primes d'assurance-maladie publique"
label variable EFPRPEN   "FÉ - Pensions de retraite privées"
label variable EFPVITX   "FÉ - Impôt provincial sur le revenu"
label variable EFPVTXC   "FÉ - Crédits d'impôt provinciaux"
label variable EFRPPC    "FÉ - Cotisations à un régime de pension agréé"
label variable EFRSPWI   "FÉ - Retraits d'un REER"
label variable EFSAPIS   "FÉ - Prestations d'assistance sociale"
label variable EFSEMP    "FÉ - Revenu net d'un travail autonome"
label variable EFTTINC   "FÉ - Revenu total avant impôt"
label variable EFUDPD    "FÉ - Cotisations syndicales (et autres primes professionnelles)"
label variable EFUIBEN   "FÉ - Prestations d'assurance-emploi"
label variable EFWGSAL   "FÉ - Salaires et traitements avant déductions"
label variable EFWKRCP   "FÉ - Indemnités pour accidents du travail"
label variable CFID      "Identificateur de la famille de recensement"
label variable CFSIZE    "Taille de la famille de recensement"
label variable CFCOMP    "Composition de la famille de recensement"
label variable CFMJIE    "Ind - Soutien économique principal de la famille de recens."
label variable CFMJIEH   "Ind - La famille de recens. inclut le soutien écon. princ. du ménage"
label variable CFRMJIG   "Lien de parenté avec soutien écon. principal de la fam. recens., rgp"
label variable CFAGOFMP  "Groupe d’âge du membre le plus âgé de la fam. de recensement"
label variable CFAGYFMP  "Groupe d’âge du membre le plus jeune de la fam. de recensement"
label variable CFMJSI    "Principale source de revenu pour la famille de recensement"
label variable CFALIMO   "FR - Pension alimentaire reçue"
label variable CFALIP    "FR - Pension alimentaire payée"
label variable CFATINC   "FR - Revenu après impôt"
label variable CFCAPGN   "FR - Gains en capital imposables"
label variable CFCCAR    "FR - Frais de garde d'enfants"
label variable CFCHFED   "FR - Total des prestations fédérales pour enfants"
label variable CFCHPRV   "FR - Total des prestations provinciales pour enfants"
label variable CFCHTXB   "FR - Total des prestations fédérales et provinciales pour enfants"
label variable CFCPQPP   "FR - Prestations du RPC/RRQ"
label variable CFCQPC    "FR - Cotisations au RPC/RRQ"
label variable CFEARNG   "FR - Revenu d'emploi"
label variable CFEIPR    "FR - Cotisations à l'assurance-emploi"
label variable CFFDITX   "FR - Impôt fédéral pour résidents du Québec"
label variable CFGI      "FR - Supplément de revenu garanti (prog. féd. Sécurité de vieillesse)"
label variable CFGSTXC   "FR - Crédit TPS/TVH fédéral (exclut crédits pour taxe de vente prov.)"
label variable CFGTR     "FR - Transferts gouvernementaux, fédéraux et provinciaux"
label variable CFINCTX   "FR - Impôt sur le revenu, fédéral et provincial"
label variable CFINVA    "FR - Revenu de placements"
label variable CFMTINC   "FR - Revenu du marché"
label variable CFOAS     "FR - Pension de la Sécurité de la vieillesse"
label variable CFOASGI   "FR - Total des prestations de Sécurité de la vieillesse"
label variable CFOGOVTR  "FR - Autres transferts gouvernementaux"
label variable CFOTHINC  "FR - Autres revenus"
label variable CFOTTXM   "FR - Autres revenus imposables"
label variable CFPEN     "FR - Pensions de retraite privées (comprend fractionn. rev. de pension"
label variable CFPENGIV  "FR - Déduction pour le montant de pension fractionné"
label variable CFPENREC  "FR - Montant de pension fractionné"
label variable CFPHPR    "FR - Primes d'assurance-maladie publique"
label variable CFPRPEN   "FR - Pensions de retraite privées"
label variable CFPVITX   "FR - Impôt provincial sur le revenu"
label variable CFPVTXC   "FR - Crédits d'impôt provinciaux"
label variable CFRPPC    "FR - Cotisations à un régime de pension agréé"
label variable CFRSPWI   "FR - Retraits d'un REER"
label variable CFSAPIS   "FR - Prestations d'assistance sociale"
label variable CFSEMP    "FR - Revenu net d'un travail autonome"
label variable CFTTINC   "FR - Revenu total avant impôt"
label variable CFUDPD    "FR - Cotisations syndicales (et autres primes professionnelles)"
label variable CFUIBEN   "FR - Prestations d'assurance-emploi"
label variable CFWGSAL   "FR - Salaires et traitements avant déductions"
label variable CFWKRCP   "FR - Indemnités pour accidents du travail"
label variable HHSIZE    "Taille du ménage"
label variable HHCOMP    "Composition du ménage"
label variable HHMJIE    "Ind - Soutien économique principal du ménage"
label variable LICODA    "Écart relatif - SFR-ApI"
label variable LICOFA    "Ind - Revenu après impôt sous le SFR-ApI"
label variable LICODB    "Écart relatif - SFR-AvI"
label variable LICOFB    "Ind - Revenu avant impôt sous le SFR-AvI"
label variable LIMSDA    "Écart relatif - MFR-ApI"
label variable LIMSFA    "Ind - Revenu après impôt sous la MFR-ApI"
label variable MBSCD18   "Écart relatif - MPC (base de 2018)"
label variable MBSCF18   "Ind - Revenu disponible sous la MPC (base de 2018)"
label variable DWLTYP    "Type de logement"
label variable DWTENR    "Mode d'occupation du logement"
label variable REPA      "État du logement"
label variable SUIT      "Ind - Logement convenable selon la Norme nationale d'occ."
label variable MORTG     "Ind - Hypothèque sur le logement"
label variable MORTGM    "Paiement hypothécaire mensuel excluant l'impôt foncier"
label variable CONDMP    "Frais de condominium mensuels"
label variable RENTM     "Loyer mensuel payé pour le ménage"
label variable RNSUB     "Ind - Loyer subventionné par gouvernement, employeur ou parent"
label variable CHNEED    "Indicateur des besoins impérieux en matière de logement"
label variable FSCADLTM  "Sécurité alimentaire - situation des adultes (incluant marginale)"
label variable FSCCHLDM  "Sécurité alimentaire - situation des enfants (incluant marginale)"
label variable FSCHHLDM  "Sécurité alimentaire - situation du ménage (incluant marginale)"
label variable VERDATE   "Date de création du fichier"
