label variable YEAR      "Reference year"
label variable PUMFID    "Household identifier"
label variable PERSONID  "Person identifier"
label variable FWEIGHT   "Final weight"
label variable PROV      "Province"
label variable USZGAP    "Adjusted size of area of residence"
label variable MBMREGP   "Market Basket Measure (MBM) Region"
label variable AGEGP     "Person's age group as of December 31 of refyear"
label variable SEX       "Sex"
label variable MARSTP    "Marital status"
label variable CMPHI     "Flag - Person completed high school"
label variable HLEV2G    "Highest level of education of person, 2nd grouping"
label variable STUDTFP   "Flag - Attended school, college, CEGEP or university during refyear"
label variable FLLPRTP   "Full-time or part-time student during refyear"
label variable FWORKED   "Flag - Person was employed during the reference year"
label variable SCSUM     "Yearly summary of time worked during the refyear"
label variable ALFST     "Annual labour force status"
label variable WKSEM     "Number of weeks employed during refyear"
label variable WKSUEM    "Number of weeks unemployed during refyear"
label variable WKSNLF    "Number of weeks not in the labour force during refyear"
label variable USHRWK    "Average usual hours worked per week at all jobs during refyear"
label variable ALHRWK    "Total usual hours worked at all jobs during refyear"
label variable FPDWK     "Flag - Person was a paid employee during refyear"
label variable FSEMP     "Flag - Person was self-employed during refyear"
label variable FUNFW     "Flag - Person was an unpaid family worker during refyear"
label variable IMMST     "Flag - Person is a landed immigrant"
label variable YRIMMG    "Number of years since person immigrated to Canada, grouping"
label variable ALIMO     "Support payments received"
label variable ALIP      "Support payments paid"
label variable ATINC     "After-tax income"
label variable CAPGN     "Taxable capital gains"
label variable CCAR      "Child care expenses"
label variable CHFED     "Total federal child benefits"
label variable CHPRV     "Total provincial child benefits"
label variable CHTXB     "Total federal and provincial child benefits"
label variable CPQPP     "CPP and QPP benefits"
label variable CQPC      "Canada and Quebec Pension Plan contributions"
label variable EARNG     "Earnings (employment income)"
label variable EIPR      "Employment Insurance contributions"
label variable FDITX     "Federal income tax (for Quebec, federal tax minus Quebec abatement)"
label variable GI        "Guaranteed Income Supplement under federal OAS"
label variable GSTXC     "Federal GST/HST Credit (excludes provincial sales tax credit)"
label variable GTR       "Government transfers, federal and provincial"
label variable INCTX     "Income tax, federal plus provincial"
label variable INVA      "Investment income"
label variable MAJRI     "Major source of income"
label variable MTINC     "Market income"
label variable OAS       "Old Age Security pension"
label variable OASGI     "Total of Old Age Security benefits"
label variable OGOVTR    "Other government transfers"
label variable OTHINC    "Other income"
label variable OTTXM     "Other taxable income"
label variable PEN       "Private retirement pensions (includes pension income splitting)"
label variable PENGIV    "Deduction for elected split-pension amount"
label variable PENREC    "Elected split-pension amount"
label variable PHPR      "Public health insurance premiums"
label variable PRPEN     "Private retirement pensions"
label variable PVITX     "Provincial income tax"
label variable PVTXC     "Provincial tax credits"
label variable RPPC      "Registered pension plan contributions"
label variable RSPWI     "RRSP withdrawals"
label variable SAPIS     "Social assistance benefits"
label variable SEMP      "Self-employment net income"
label variable TTINC     "Total income before taxes"
label variable UDPD      "Union dues (and other professional premiums)"
label variable UIBEN     "Employment Insurance benefits"
label variable WGSAL     "Wages and salaries before deductions"
label variable WKRCP     "Workers' compensation benefits"
label variable EFID      "Economic family identifier"
label variable EFSIZE    "Number of economic family members"
label variable EFTYP     "Economic family type"
label variable EFMJIE    "Flag - Major income earner in the economic family"
label variable EFMJIEH   "Flag - Economic family includes major income earner of household"
label variable EFRMJIG   "Relationship to major income earner in economic family, group"
label variable EFAGOFMP  "Age group of oldest person in economic family"
label variable EFAGYFMP  "Age group of youngest person in economic family"
label variable EFMJSI    "Major source of income for the economic family"
label variable EFALIMO   "EF - Support payments received"
label variable EFALIP    "EF - Support payments paid"
label variable EFATINC   "EF - After-tax income"
label variable EFCAPGN   "EF - Taxable capital gains"
label variable EFCCAR    "EF - Child care expenses"
label variable EFCHFED   "EF - Total federal child benefits"
label variable EFCHPRV   "EF - Total provincial child benefits"
label variable EFCHTXB   "EF - Total federal and provincial child benefits"
label variable EFCPQPP   "EF - CPP and QPP benefits"
label variable EFCQPC    "EF - Canada and Quebec Pension Plan contributions"
label variable EFEARNG   "EF - Earnings (employment income)"
label variable EFEIPR    "EF - Employment Insurance contributions"
label variable EFFDITX   "EF - Federal income tax for Quebec residents"
label variable EFGI      "EF - Guaranteed Income Supplement under federal OAS"
label variable EFGSTXC   "EF - Federal GST/HST Credit (excludes provincial sales tax credit)"
label variable EFGTR     "EF - Government transfers, federal and provincial"
label variable EFINCTX   "EF - Income tax, federal plus provincial"
label variable EFINVA    "EF - Investment income"
label variable EFMBIN18  "EF - Disposable income for Market Basket Measure (2018 base)"
label variable EFMTINC   "EF - Market income"
label variable EFOAS     "EF - Old Age Security pension"
label variable EFOASGI   "EF - Total of Old Age Security benefits"
label variable EFOGOVTR  "EF - Other government transfers"
label variable EFOTHINC  "EF - Other income"
label variable EFOTTXM   "EF - Other taxable income"
label variable EFPEN     "EF - Private retirement pensions (includes pension income splitting)"
label variable EFPENGIV  "EF - Deduction for elected split-pension amount"
label variable EFPENREC  "EF - Elected split-pension amount"
label variable EFPHPR    "EF - Public health insurance premiums"
label variable EFPRPEN   "EF - Private retirement pensions"
label variable EFPVITX   "EF - Provincial income tax"
label variable EFPVTXC   "EF - Provincial tax credits"
label variable EFRPPC    "EF - Registered pension plan contributions"
label variable EFRSPWI   "EF - RRSP withdrawals"
label variable EFSAPIS   "EF - Social assistance benefits"
label variable EFSEMP    "EF - Self-employment net income"
label variable EFTTINC   "EF - Total income before taxes"
label variable EFUDPD    "EF - Union dues (and other professional premiums)"
label variable EFUIBEN   "EF - Employment Insurance benefits"
label variable EFWGSAL   "EF - Wages and salaries before deductions"
label variable EFWKRCP   "EF - Workers' compensation benefits"
label variable CFID      "Census family identifier"
label variable CFSIZE    "Number of census family members"
label variable CFCOMP    "Census family composition"
label variable CFMJIE    "Flag - Major income earner in the census family"
label variable CFMJIEH   "Flag - Census family includes major income earner of household"
label variable CFRMJIG   "Relationship to major income earner in census family, group"
label variable CFAGOFMP  "Age group of oldest person in census family"
label variable CFAGYFMP  "Age group of youngest person in census family"
label variable CFMJSI    "Major source of income for the census family"
label variable CFALIMO   "CF - Support payments received"
label variable CFALIP    "CF - Support payments paid"
label variable CFATINC   "CF - After-tax income"
label variable CFCAPGN   "CF - Taxable capital gains"
label variable CFCCAR    "CF - Child care expenses"
label variable CFCHFED   "CF - Total federal child benefits"
label variable CFCHPRV   "CF - Total provincial child benefits"
label variable CFCHTXB   "CF - Total federal and provincial child benefits"
label variable CFCPQPP   "CF - CPP and QPP benefits"
label variable CFCQPC    "CF - Canada and Quebec Pension Plan contributions"
label variable CFEARNG   "CF - Earnings (employment income)"
label variable CFEIPR    "CF - Employment Insurance contributions"
label variable CFFDITX   "CF - Federal income tax for Quebec residents"
label variable CFGI      "CF - Guaranteed Income Supplement under federal OAS"
label variable CFGSTXC   "CF - Federal GST/HST Credit (excludes provincial sales tax credit)"
label variable CFGTR     "CF - Government transfers, federal and provincial"
label variable CFINCTX   "CF - Income tax, federal plus provincial"
label variable CFINVA    "CF - Investment income"
label variable CFMTINC   "CF - Market income"
label variable CFOAS     "CF - Old Age Security pension"
label variable CFOASGI   "CF - Total of Old Age Security benefits"
label variable CFOGOVTR  "CF - Other government transfers"
label variable CFOTHINC  "CF - Other income"
label variable CFOTTXM   "CF - Other taxable income"
label variable CFPEN     "CF - Private retirement pensions (includes pension income splitting)"
label variable CFPENGIV  "CF - Deduction for elected split-pension amount"
label variable CFPENREC  "CF - Elected split-pension amount"
label variable CFPHPR    "CF - Public health insurance premiums"
label variable CFPRPEN   "CF - Private retirement pensions"
label variable CFPVITX   "CF - Provincial income tax"
label variable CFPVTXC   "CF - Provincial tax credits"
label variable CFRPPC    "CF - Registered pension plan contributions"
label variable CFRSPWI   "CF - RRSP withdrawals"
label variable CFSAPIS   "CF - Social assistance benefits"
label variable CFSEMP    "CF - Self-employment net income"
label variable CFTTINC   "CF - Total income before taxes"
label variable CFUDPD    "CF - Union dues (and other professional premiums)"
label variable CFUIBEN   "CF - Employment Insurance benefits"
label variable CFWGSAL   "CF - Wages and salaries before deductions"
label variable CFWKRCP   "CF - Workers' compensation benefits"
label variable HHSIZE    "Number of household members"
label variable HHCOMP    "Household composition"
label variable HHMJIE    "Flag - Major income earner in the household"
label variable LICODA    "Gap ratio - LICO-AT"
label variable LICOFA    "Flag - After-tax income below LICO-AT"
label variable LICODB    "Gap ratio -  LICO-BT"
label variable LICOFB    "Flag - Before-tax income below LICO-BT"
label variable LIMSDA    "Gap ratio -  LIM-AT"
label variable LIMSFA    "Flag - After-tax income below LIM-AT"
label variable MBSCD18   "Gap ratio - MBM (2018 base)"
label variable MBSCF18   "Flag - Disposable income below MBM (2018 base)"
label variable DWLTYP    "Type of dwelling"
label variable DWTENR    "Ownership of dwelling"
label variable REPA      "Condition of dwelling"
label variable SUIT      "Flag - Dwelling suitable, according to Nat. Occ. Standard"
label variable MORTG     "Flag - Mortgage on dwelling"
label variable MORTGM    "Monthly mortgage payment, excluding property taxes, for the household"
label variable CONDMP    "Monthly condominium fee"
label variable RENTM     "Monthly rent paid for the household"
label variable RNSUB     "Flag - Rent subsidized by government, employer or relative"
label variable CHNEED    "Core housing need indicator"
label variable FSCADLTM  "Food security - adult status (including marginally)"
label variable FSCCHLDM  "Food security - child status (including marginally)"
label variable FSCHHLDM  "Food security - household status (including marginally)"
label variable VERDATE   "Date of file creation"
