label values   ALHRWK    ALHRWK_FMT
label values   ALIMO     ALIMO_FMT
label values   ALIP      ALIP_FMT
label values   ATINC     ATINC_FMT
label values   CAPGN     CAPGN_FMT
label values   CCAR      CCAR_FMT
label values   CFALIMO   CFALIMO_FMT
label values   CFALIP    CFALIP_FMT
label values   CFATINC   CFATINC_FMT
label values   CFCAPGN   CFCAPGN_FMT
label values   CFCCAR    CFCCAR_FMT
label values   CFCHFED   CFCHFED_FMT
label values   CFCHPRV   CFCHPRV_FMT
label values   CFCHTXB   CFCHTXB_FMT
label values   CFCPQPP   CFCPQPP_FMT
label values   CFCQPC    CFCQPC_FMT
label values   CFEARNG   CFEARNG_FMT
label values   CFEIPR    CFEIPR_FMT
label values   CFFDITX   CFFDITX_FMT
label values   CFGI      CFGI_FMT
label values   CFGSTXC   CFGSTXC_FMT
label values   CFGTR     CFGTR_FMT
label values   CFINCTX   CFINCTX_FMT
label values   CFINVA    CFINVA_FMT
label values   CFMTINC   CFMTINC_FMT
label values   CFOAS     CFOAS_FMT
label values   CFOASGI   CFOASGI_FMT
label values   CFOGOVTR  CFOGOVTR_FMT
label values   CFOTHINC  CFOTHINC_FMT
label values   CFOTTXM   CFOTTXM_FMT
label values   CFPEN     CFPEN_FMT
label values   CFPENGIV  CFPENGIV_FMT
label values   CFPENREC  CFPENREC_FMT
label values   CFPHPR    CFPHPR_FMT
label values   CFPRPEN   CFPRPEN_FMT
label values   CFPVITX   CFPVITX_FMT
label values   CFPVTXC   CFPVTXC_FMT
label values   CFRPPC    CFRPPC_FMT
label values   CFRSPWI   CFRSPWI_FMT
label values   CFSAPIS   CFSAPIS_FMT
label values   CFSEMP    CFSEMP_FMT
label values   CFSIZE    CFSIZE_FMT
label values   CFTTINC   CFTTINC_FMT
label values   CFUDPD    CFUDPD_FMT
label values   CFUIBEN   CFUIBEN_FMT
label values   CFWGSAL   CFWGSAL_FMT
label values   CFWKRCP   CFWKRCP_FMT
label values   CHFED     CHFED_FMT
label values   CHPRV     CHPRV_FMT
label values   CHTXB     CHTXB_FMT
label values   CONDMP    CONDMP_FMT
label values   CPQPP     CPQPP_FMT
label values   CQPC      CQPC_FMT
label values   EARNG     EARNG_FMT
label values   EFALIMO   EFALIMO_FMT
label values   EFALIP    EFALIP_FMT
label values   EFATINC   EFATINC_FMT
label values   EFCAPGN   EFCAPGN_FMT
label values   EFCCAR    EFCCAR_FMT
label values   EFCHFED   EFCHFED_FMT
label values   EFCHPRV   EFCHPRV_FMT
label values   EFCHTXB   EFCHTXB_FMT
label values   EFCPQPP   EFCPQPP_FMT
label values   EFCQPC    EFCQPC_FMT
label values   EFEARNG   EFEARNG_FMT
label values   EFEIPR    EFEIPR_FMT
label values   EFFDITX   EFFDITX_FMT
label values   EFGI      EFGI_FMT
label values   EFGSTXC   EFGSTXC_FMT
label values   EFGTR     EFGTR_FMT
label values   EFINCTX   EFINCTX_FMT
label values   EFINVA    EFINVA_FMT
label values   EFMBIN18  EFMBIN18_FMT
label values   EFMTINC   EFMTINC_FMT
label values   EFOAS     EFOAS_FMT
label values   EFOASGI   EFOASGI_FMT
label values   EFOGOVTR  EFOGOVTR_FMT
label values   EFOTHINC  EFOTHINC_FMT
label values   EFOTTXM   EFOTTXM_FMT
label values   EFPEN     EFPEN_FMT
label values   EFPENGIV  EFPENGIV_FMT
label values   EFPENREC  EFPENREC_FMT
label values   EFPHPR    EFPHPR_FMT
label values   EFPRPEN   EFPRPEN_FMT
label values   EFPVITX   EFPVITX_FMT
label values   EFPVTXC   EFPVTXC_FMT
label values   EFRPPC    EFRPPC_FMT
label values   EFRSPWI   EFRSPWI_FMT
label values   EFSAPIS   EFSAPIS_FMT
label values   EFSEMP    EFSEMP_FMT
label values   EFSIZE    EFSIZE_FMT
label values   EFTTINC   EFTTINC_FMT
label values   EFUDPD    EFUDPD_FMT
label values   EFUIBEN   EFUIBEN_FMT
label values   EFWGSAL   EFWGSAL_FMT
label values   EFWKRCP   EFWKRCP_FMT
label values   EIPR      EIPR_FMT
label values   FDITX     FDITX_FMT
label values   GI        GI_FMT
label values   GSTXC     GSTXC_FMT
label values   GTR       GTR_FMT
label values   HHSIZE    HHSIZE_FMT
label values   INCTX     INCTX_FMT
label values   INVA      INVA_FMT
label values   MORTGM    MORTGM_FMT
label values   MTINC     MTINC_FMT
label values   OAS       OAS_FMT
label values   OASGI     OASGI_FMT
label values   OGOVTR    OGOVTR_FMT
label values   OTHINC    OTHINC_FMT
label values   OTTXM     OTTXM_FMT
label values   PEN       PEN_FMT
label values   PENGIV    PENGIV_FMT
label values   PENREC    PENREC_FMT
label values   PHPR      PHPR_FMT
label values   PRPEN     PRPEN_FMT
label values   PVITX     PVITX_FMT
label values   PVTXC     PVTXC_FMT
label values   RENTM     RENTM_FMT
label values   RPPC      RPPC_FMT
label values   RSPWI     RSPWI_FMT
label values   SAPIS     SAPIS_FMT
label values   SEMP      SEMP_FMT
label values   TTINC     TTINC_FMT
label values   UDPD      UDPD_FMT
label values   UIBEN     UIBEN_FMT
label values   WGSAL     WGSAL_FMT
label values   WKRCP     WKRCP_FMT
label values   WKSEM     WKSEM_FMT
label values   WKSNLF    WKSNLF_FMT
label values   WKSUEM    WKSUEM_FMT
